Pytest:
  script: |
    curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/build-and-test-py-project.sh
    . ./build-and-test-py-project.sh
  tags:
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Ruff:
  script:
  - pipx install ruff
  - ruff check
  tags:
  - docker-runner
  except:
  - tags

Mypy:
  script:
  - curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/prepare-and-run-mypy.sh
  - ". ./prepare-and-run-mypy.sh python3 mypy"
  tags:
  - python3
  except:
  - tags

Pylint:
  script:
  - curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/prepare-and-run-pylint.sh
  - . ./prepare-and-run-pylint.sh "$CI_PROJECT_NAME"
  tags:
  - python3
  except:
  - tags

Documentation:
  script:
  - curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3

# vim: sw=2
